// grid dummy data
var labs = {
	"01 - Introduction":`<link rel="stylesheet" type="text/css" href="css/Lab0/Lab0.css" />
	<div class="container">
	<h2>Personal Information Page</h2><p>Link for page <b><a href="css/Lab0/Lab0.css">CSS</a></b></p><div class="panel-group" id="accordion"><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1"  class="no-deco">Basic Info</a></h4></div><div id="collapse1" class="panel-collapse collapse in"><div class="panel-body text-left" style="color:black;"><p>Hey, my name is <b>Shomik Ghose</b>, here is some basic info about me:</p><ul><li>16 years old</li><li>11th grader at TJHSST</li><li>Born on March 5th</li><li>One older brother</li></ul></div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse2" class="no-deco">Favourite Ways to Waste Time</a></h4></div><div id="collapse2" class="panel-collapse collapse"><div class="panel-body text-left" style="color:black;"><p>I play <b>a lot</b> more games than I should - currently addicted to:</p><ul><li>League of Legends</li><li>Hearthstone</li><li>Chess <i>(I am pretty bad though)</i></li></ul><p>Additionally, like many, I can waste hours on end on <b><a href="http:www.reddit.com" style="color:black;">reddit</a></b></p></div></div></div><div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse3"  class="no-deco">Academic Interests</a></h4></div><div id="collapse3" class="panel-collapse collapse"><div class="panel-body text-left" style="color:black;">I\'m interested mostly in <b>Bio</b> and compete in USABO/Brain Bee. I\'m currently the MDVA Nationals Representative for Brain Bee and hope to not fail as spectacularly as last year and get into USABO camp this year! <br><br> I hope to attend <b>Oxford</b> Undergraduate Medical program after High School!<br><br><i>(Assuming my GPA survives AP Physics that is)</i></div></div></div></div></div>`,
	"02 - Quiz":'<div class="container"><section><h1 id="title"><b>Neuro</b>anatomy</h1><h5 id="title">So this does work, I was just too lazy to fix it after the transfer to C9, check the original index for the working version</h5><div id="responseStatus" class="alert alert-info" role="alert">Submit an answer to start the game!</div><div><h2><div class="col-xs-4 text-left"><span id="numCorrect" class="label label-primary">Correct: 0</span><span id="numIncorrect" class="label label-danger">Incorrect: 0</span></div><div class="col-xs-8 text-right"><span id="numLeft" class="label label-info">Unused: 109</span></div></h2></div><div class="row"><div class="span4"><div style="height: 200px; width: 100%; font-size: 0; margin: 0; padding: 0; border: 0; display: block"></div></div></div><div class="progress"><div id="timeLeft" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:100%">2:00</div></div><div class="input-group input-group-lg"><input id="response" type="text" class="form-control" placeholder="Neural Feature" onkeydown = "if (event.keyCode == 13) {document.getElementById("submit").click() }" autofocus><span class="input-group-btn"><button id="submit" class="btn btn-primary" type="button" onclick="quizFunc()">Submit</button></span></div><br><div "navbar-static-bottom" id="footer"><div class="col-xs-3 text-left"><button id="pauseButton" type="button" class="btn btn-info" onclick="pause()">Pause</button></div><div class="col-xs-6 text-center"><div class="btn-group" data-toggle="buttons"><label id="radio1" class="btn btn-primary active"><input type="radio" name="options" id="option1" autocomplete="off" checked> Basic Regions</label><label id="radio2" class="btn btn-primary"><input type="radio" name="options" id="option2" autocomplete="off"> Cranial Nerves</label><label id="radio3" class="btn btn-primary"><input type="radio" name="options" id="option3" autocomplete="off"> Neural Arteries</label></div></div><div class="col-xs-3 text-right"><button type="button" class="btn btn-info" onclick="restart()">Restart</button></div></div></section><script src="Lab1.js"></script></div><script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script><script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>'
	
	
	
	
	
	
};